name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - task: SonarCloudPrepare@1
        name: "Prepare analysis on SonarCloud"
        inputs:
          organization: ramji-01
          projectKey: ramji-01_Airline
          extraProperties: |
            sonar.verbose=true
            sonar.sourceEncoding=UTF-8
            sonar.language=ts
            sonar.tests=src
            sonar.test.inclusions=**/*.spec.ts
            sonar.typescript.lcov.reportPaths=coverage/AirlineMangement-Client-Main/lcov.info
            sonar.testExecutionReportPaths=reports/sonarcloud_report.xml
      - task: SonarCloudAnalyze@1
        displayName: "Run SonarCloud analysis"
      - task: SonarCloudPublish@1
        displayName: "Publish results on build summary"
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
